DROP TABLE IF EXISTS appliedonline_customers CASCADE;

CREATE TABLE appliedonline_customers (
  customers_id UUID NOT NULL,
  id BIGSERIAL,
  prefix varchar(10) DEFAULT NULL,
  cus_name varchar(200) DEFAULT NULL,
  cus_mobile varchar(10) DEFAULT NULL,
  cus_phone varchar(20) DEFAULT NULL,
  cus_email varchar(100) DEFAULT NULL,
  cus_address text DEFAULT NULL,
  houseno varchar(30) DEFAULT NULL,
  cus_state varchar(50) DEFAULT NULL,
  cus_city varchar(50) DEFAULT NULL,
  cus_location varchar(100) DEFAULT NULL,
  cus_pincode varchar(20) DEFAULT NULL,
  postoffice varchar(50) DEFAULT NULL,
  cus_conn_type varchar(30) DEFAULT NULL,
  rationcard varchar(100) DEFAULT NULL,
  cus_speed varchar(30) DEFAULT NULL,
  status varchar(100) DEFAULT 'open',
  telcall_status varchar(100) DEFAULT 'Not Dialed (ND)',
  description text DEFAULT NULL,
  remarks text DEFAULT NULL,
  circle varchar(50) DEFAULT NULL,
  region varchar(50) DEFAULT NULL,
  created_dt timestamp DEFAULT NULL,
  updated_dt timestamp DEFAULT NULL,
  partnername varchar(256) DEFAULT NULL,
  partnerid bigint DEFAULT NULL,
  partnercontact varchar(12) DEFAULT NULL,
  dmkg int DEFAULT NULL,
  previous_cmnts text DEFAULT NULL,
  previous_cmnts1 text DEFAULT NULL,
  district_code varchar(20) DEFAULT NULL,
  popname varchar(256) DEFAULT NULL,
  location varchar(256) DEFAULT NULL,
  endoffice_name varchar(256) DEFAULT NULL,
  linedepartment varchar(256) DEFAULT NULL,
  secdepartment varchar(256) DEFAULT NULL,
  mail_sent smallint DEFAULT 0,
  sms_sent smallint DEFAULT 0,
  fe_name varchar(50) DEFAULT NULL,
  tracking_id varchar(10) DEFAULT NULL,
  e_flag smallint DEFAULT 1,
  reference varchar(50) DEFAULT NULL,
  campaign_id int DEFAULT NULL,
  ticket_id int DEFAULT NULL,
  created_by int DEFAULT NULL,
  Imported_date timestamp DEFAULT NULL,
  old_status varchar(255) DEFAULT NULL,
  latitude varchar(100) DEFAULT NULL,
  longitude varchar(100) DEFAULT NULL,
  followupdate date DEFAULT NULL,
  connectiondate date DEFAULT NULL,
  create_date timestamp DEFAULT CURRENT_TIMESTAMP,
  update_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  kseb_consumerno varchar(13) DEFAULT NULL,
  nearest_partnerid varchar(50) DEFAULT NULL,
  nearest_partnername varchar(100) DEFAULT NULL,
  nearest_partnermobile varchar(12) DEFAULT NULL,
  nearest_ptnr_distance varchar(100) DEFAULT NULL,
  near_fe_id varchar(20) DEFAULT NULL,
  near_fe_emp_name varchar(50) DEFAULT NULL,
  near_fe_username varchar(50) DEFAULT NULL,
  nearest_subid varchar(100) DEFAULT NULL,
  nearest_subname varchar(100) DEFAULT NULL,
  nearest_sub_distance varchar(100) DEFAULT NULL,
  nearest_sub_ptnrid varchar(50) DEFAULT NULL,
  nearest_sub_ptnrname varchar(100) DEFAULT NULL,
  nearest_sub_ptnrmobile varchar(12) DEFAULT NULL,
  nearest_Equipment_Name varchar(100) DEFAULT NULL,
  nearest_equi_distance varchar(100) DEFAULT NULL,
  nearest_Equipment_popname varchar(100) DEFAULT NULL,
  nearest_Equipment_lat varchar(100) DEFAULT NULL,
  nearest_Equipment_lon varchar(100) DEFAULT NULL,
  referral_code varchar(100) DEFAULT NULL,
  aadhar_number varchar(12) DEFAULT NULL,
  ration_card_type varchar(200) DEFAULT NULL,
  nearest_landmark varchar(500) DEFAULT NULL,
  original_enq_id varchar(100) DEFAULT NULL,
  subscriberid varchar(100) DEFAULT NULL,
  oltabid varchar(100) DEFAULT NULL,
  package varchar(100) DEFAULT NULL,
  is_existing_cus varchar(100) DEFAULT NULL,
  CONSTRAINT pk_appliedonline_customers PRIMARY KEY (customers_id)
);

CREATE INDEX circle_idx ON appliedonline_customers (circle);
CREATE INDEX region_idx ON appliedonline_customers (region);
CREATE INDEX cus_name_idx ON appliedonline_customers (cus_name);
CREATE INDEX cus_mobile_idx ON appliedonline_customers (cus_mobile);
CREATE INDEX created_dt_idx ON appliedonline_customers (created_dt);
CREATE INDEX status_idx ON appliedonline_customers (status);

