DROP TABLE IF EXISTS cor_fin_mspinvoicing_BKP CASCADE;

CREATE TABLE cor_fin_mspinvoicing_BKP (
  id UUID NOT NULL,
  slno SERIAL,
  invoicemonth varchar(20) DEFAULT NULL,
  status varchar(30) DEFAULT NULL,
  state varchar(50) DEFAULT NULL,
  remarks varchar(100) DEFAULT NULL,
  mspid bigint DEFAULT NULL,
  designation varchar(50) DEFAULT NULL,
  verifiedby varchar(50) DEFAULT NULL,
  approvedate timestamp DEFAULT NULL,
  invoiceno varchar(50) DEFAULT NULL,
  nettotal decimal(10,2) DEFAULT NULL,
  STtotal decimal(10,2) DEFAULT NULL,
  GrossTotal decimal(10,2) DEFAULT NULL,
  dot decimal(10,2) DEFAULT NULL,
  agrtotal decimal(10,2) DEFAULT NULL,
  mktshare decimal(10,2) DEFAULT NULL,
  mspshare decimal(10,2) DEFAULT NULL,
  netshare decimal(10,2) DEFAULT NULL,
  STpartner decimal(10,2) DEFAULT NULL,
  GrossShare decimal(10,2) DEFAULT NULL,
  TDSpartner decimal(10,2) DEFAULT NULL,
  NetPayable decimal(10,2) DEFAULT NULL,
  STno varchar(30) DEFAULT NULL,
  Pan varchar(20) DEFAULT NULL,
  requestdate timestamp DEFAULT NULL,
  edcess decimal(10,2) DEFAULT NULL,
  secedcess decimal(10,2) DEFAULT NULL,
  STpartnertotal decimal(10,2) DEFAULT NULL,
  prsshare decimal(10,2) DEFAULT NULL,
  modifiedby varchar(50) DEFAULT NULL,
  modifiedon timestamp DEFAULT NULL,
  spocapproval int DEFAULT NULL,
  spocapproval_date timestamp DEFAULT NULL,
  rrit_response varchar(300) DEFAULT NULL,
  rrit_response_date timestamp DEFAULT NULL,
  mspresponse varchar(300) DEFAULT NULL,
  msp_response_date timestamp DEFAULT NULL,
  spocremark varchar(300) DEFAULT NULL,
  spocresponse varchar(200) NOT NULL,
  workorderid varchar(45) DEFAULT NULL,
  CONSTRAINT pk_cor_fin_mspinvoicing_BKP PRIMARY KEY (id)
);


DROP TABLE IF EXISTS cor_fin_mspinvoicing_breakup CASCADE;

CREATE TABLE cor_fin_mspinvoicing_breakup (
  id UUID NOT NULL,
  slno int NOT NULL DEFAULT 0,
  invoicemonth varchar(20) DEFAULT NULL,
  status varchar(30) DEFAULT NULL,
  state varchar(50) DEFAULT NULL,
  remarks varchar(100) DEFAULT NULL,
  mspid bigint DEFAULT NULL,
  designation varchar(50) DEFAULT NULL,
  verifiedby varchar(50) DEFAULT NULL,
  approvedate timestamp DEFAULT NULL,
  invoiceno varchar(50) DEFAULT NULL,
  nettotal decimal(10,2) DEFAULT NULL,
  STtotal decimal(10,2) DEFAULT NULL,
  GrossTotal decimal(10,2) DEFAULT NULL,
  dot decimal(10,2) DEFAULT NULL,
  agrtotal decimal(10,2) DEFAULT NULL,
  mktshare decimal(10,2) DEFAULT NULL,
  mspshare decimal(10,2) DEFAULT NULL,
  netshare decimal(10,2) DEFAULT NULL,
  STpartner decimal(10,2) DEFAULT NULL,
  GrossShare decimal(10,2) DEFAULT NULL,
  TDSpartner decimal(10,2) DEFAULT NULL,
  NetPayable decimal(10,2) DEFAULT NULL,
  STno varchar(30) DEFAULT NULL,
  Pan varchar(20) DEFAULT NULL,
  requestdate timestamp DEFAULT NULL,
  edcess decimal(10,2) DEFAULT NULL,
  secedcess decimal(10,2) DEFAULT NULL,
  STpartnertotal decimal(10,2) DEFAULT NULL,
  prsshare decimal(10,2) DEFAULT NULL,
  modifiedby varchar(50) DEFAULT NULL,
  modifiedon timestamp DEFAULT NULL,
  spocapproval int DEFAULT NULL,
  spocapproval_date timestamp DEFAULT NULL,
  rrit_response varchar(300) DEFAULT NULL,
  rrit_response_date timestamp DEFAULT NULL,
  mspresponse varchar(300) DEFAULT NULL,
  msp_response_date timestamp DEFAULT NULL,
  spocremark varchar(300) DEFAULT NULL,
  spocresponse varchar(300) DEFAULT NULL,
  workorderid varchar(45) DEFAULT NULL,
  sbcess decimal(10,2) DEFAULT 0.00,
  kkcess decimal(10,2) DEFAULT NULL,
  pamount decimal(10,2) DEFAULT NULL,
  gst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  cgst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  sgst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  igst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  gst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  cgst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  sgst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  igst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  gstin varchar(15) DEFAULT NULL,
  gst_disburse_status boolean NOT NULL DEFAULT false,
  STCode char(3) DEFAULT NULL,
  paid_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  cgsttds_amount decimal(13,2) DEFAULT 0.00,
  sgsttds_amount decimal(13,2) DEFAULT 0.00,
  CONSTRAINT pk_cor_fin_mspinvoicing_breakup PRIMARY KEY (id)
);


DROP TABLE IF EXISTS cor_lco_agp_approve CASCADE;

CREATE TABLE cor_lco_agp_approve (
  approve_id UUID NOT NULL,
  slno int NOT NULL DEFAULT 0,
  imonth varchar(10) DEFAULT NULL,
  approvedby varchar(100) DEFAULT NULL,
  status varchar(20) DEFAULT NULL,
  statecode varchar(5) DEFAULT NULL,
  time_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  approvedon timestamp DEFAULT NULL,
  remarks varchar(250) DEFAULT NULL,
  modifiedby varchar(100) DEFAULT NULL,
  modifiedon timestamp DEFAULT NULL,
  spocapproval varchar(25) DEFAULT NULL,
  spocapprovedate timestamp DEFAULT NULL,
  CONSTRAINT pk_cor_lco_agp_approve PRIMARY KEY (approve_id)
);


DROP TABLE IF EXISTS cor_lco_agp_list CASCADE;

CREATE TABLE cor_lco_agp_list (
  id UUID NOT NULL,
  slno SERIAL,
  imonth varchar(10) DEFAULT NULL,
  partnerid varchar(25) DEFAULT NULL,
  partnername varchar(150) DEFAULT NULL,
  statecode varchar(5) DEFAULT NULL,
  agpid varchar(25) DEFAULT NULL,
  agpname varchar(150) DEFAULT NULL,
  CONSTRAINT pk_cor_lco_agp_list PRIMARY KEY (id)
);


DROP TABLE IF EXISTS cor_monthlyinvoice CASCADE;

CREATE TABLE cor_monthlyinvoice (
  invoice_id UUID NOT NULL,
  slno SERIAL,
  subgroup boolean DEFAULT NULL,
  type boolean DEFAULT true,
  wid varchar(30) DEFAULT NULL,
  cause varchar(30) DEFAULT NULL,
  pgid int NOT NULL,
  locid int DEFAULT NULL,
  packageid int DEFAULT NULL,
  subid bigint DEFAULT NULL,
  disbid int NOT NULL,
  mdisbid int DEFAULT NULL,
  disb_status boolean DEFAULT NULL,
  disb_date timestamp DEFAULT NULL,
  ssdate timestamp DEFAULT NULL,
  sedate timestamp DEFAULT NULL,
  revenueshareid int DEFAULT 0,
  revenue decimal(26,10) DEFAULT 0.0000000000,
  ibnpid bigint DEFAULT 0,
  ibnp_share decimal(26,10) DEFAULT 0.0000000000,
  ibnp_percent decimal(5,2) DEFAULT NULL,
  anpid bigint DEFAULT 0,
  anp_share decimal(26,10) DEFAULT 0.0000000000,
  anp_percent decimal(5,2) DEFAULT NULL,
  prsid bigint DEFAULT 0,
  prs_share decimal(26,10) DEFAULT 0.0000000000,
  prs_percent decimal(5,2) DEFAULT NULL,
  ibwpid bigint DEFAULT 0,
  ibwp_share decimal(26,10) DEFAULT 0.0000000000,
  ibwp_percent decimal(5,2) DEFAULT NULL,
  cnpid bigint DEFAULT 0,
  cnp_share decimal(26,10) DEFAULT 0.0000000000,
  cnp_percent decimal(5,2) DEFAULT NULL,
  mktid bigint DEFAULT 0,
  mkt_share decimal(26,10) DEFAULT 0.0000000000,
  mkt_percent decimal(5,2) DEFAULT NULL,
  permid bigint DEFAULT 0,
  perm_share decimal(26,10) DEFAULT 0.0000000000,
  perm_percent decimal(5,2) DEFAULT NULL,
  agpid bigint DEFAULT 0,
  agp_share decimal(26,10) DEFAULT 0.0000000000,
  agp_percent decimal(5,2) DEFAULT NULL,
  mspid bigint DEFAULT 0,
  msp_share decimal(26,10) DEFAULT 0.0000000000,
  msp_percent decimal(5,2) DEFAULT NULL,
  ispid bigint DEFAULT 0,
  isp_share decimal(26,10) DEFAULT 0.0000000000,
  isp_percent decimal(5,2) DEFAULT NULL,
  dot_percent decimal(5,2) DEFAULT NULL,
  dot_share decimal(12,4) DEFAULT 0.0000,
  statecode varchar(10) DEFAULT '0',
  pst_code varchar(10) DEFAULT '0',
  revenue_type varchar(20) DEFAULT '0',
  monthpart varchar(20) DEFAULT '0',
  online int DEFAULT 0,
  remarks varchar(100) DEFAULT NULL,
  create_date timestamp DEFAULT CURRENT_TIMESTAMP,
  update_date timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cor_monthlyinvoice PRIMARY KEY (invoice_id)
);

COMMENT ON COLUMN cor_monthlyinvoice.subgroup IS '1-enterprise,2-govt,3-darkfiber,4-specialevent,5-BPL';
COMMENT ON COLUMN cor_monthlyinvoice.invoice_id IS 'Unique identifier for COR monthly invoice records';