-- Table : fin_lcoinvoicing
DROP TABLE IF EXISTS fin_lcoinvoicing CASCADE;

CREATE TABLE fin_lcoinvoicing (
  fin_lcoinvoicing_id UUID DEFAULT gen_random_uuid() NOT NULL,
  slno SERIAL,
  invoicemonth varchar(20) DEFAULT NULL,
  status INT DEFAULT NULL,
  state varchar(50) DEFAULT NULL,
  address varchar(300) DEFAULT NULL,
  remarks varchar(100) DEFAULT NULL,
  partnerid bigint DEFAULT NULL,
  designation varchar(50) DEFAULT NULL,
  verifiedby varchar(50) DEFAULT NULL,
  approvedate timestamp DEFAULT NULL,
  invoiceno varchar(50) DEFAULT NULL,
  nettotal decimal(10,2) DEFAULT NULL,
  STtotal decimal(10,2) DEFAULT NULL,
  GrossTotal decimal(10,2) DEFAULT NULL,
  dot decimal(10,2) DEFAULT NULL,
  agrtotal decimal(10,2) DEFAULT NULL,
  ibnpshare decimal(10,2) DEFAULT NULL,
  anpshare decimal(10,2) DEFAULT NULL,
  incentive decimal(10,2) DEFAULT NULL,
  anpewsshare decimal(10,2) DEFAULT NULL,
  netshare decimal(10,2) DEFAULT NULL,
  STpartner decimal(10,2) DEFAULT NULL,
  GrossShare decimal(10,2) DEFAULT NULL,
  TDSpartner decimal(10,2) DEFAULT NULL,
  NetPayable decimal(10,2) DEFAULT NULL,
  STno varchar(25) DEFAULT NULL,
  Pan varchar(12) DEFAULT NULL,
  requestdate timestamp DEFAULT NULL,
  cnpshare decimal(10,2) DEFAULT NULL,
  agnpshare decimal(10,2) DEFAULT NULL,
  mktshare decimal(10,2) DEFAULT NULL,
  prsshare decimal(10,2) DEFAULT NULL,
  mspshare decimal(10,2) DEFAULT NULL,
  gsround decimal(10,2) DEFAULT NULL,
  tdsround decimal(10,2) DEFAULT NULL,
  response varchar(256) DEFAULT NULL,
  responsedate timestamp DEFAULT NULL,
  sbcess decimal(10,2) DEFAULT 0.00,
  kkcess decimal(10,2) DEFAULT NULL,
  deemedappvdate timestamp DEFAULT NULL,
  gst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  cgst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  sgst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  igst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  gst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  cgst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  sgst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  igst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  paid_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  gstin varchar(15) DEFAULT NULL,
  gst_disburse_status INT NOT NULL DEFAULT 0,
  STCode char(3) DEFAULT NULL,
  pst_code char(3) DEFAULT NULL,
  taxpayertype INT NOT NULL DEFAULT 0,
  gst_disbursedate timestamp DEFAULT NULL,
  eligible_revenue decimal(13,2) DEFAULT NULL,
  cgst_tds decimal(13,2) NOT NULL DEFAULT 0.00,
  sgst_tds decimal(13,2) NOT NULL DEFAULT 0.00,
  cgsttds_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  sgsttds_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  normalrevenue decimal(12,2) DEFAULT NULL,
  ewsrevenue decimal(12,2) DEFAULT NULL,
  cashbackcur decimal(10,2) DEFAULT NULL,
  cashbackrev decimal(10,2) DEFAULT NULL,
  cashbackshare decimal(10,2) DEFAULT NULL,
  total_subs int DEFAULT NULL,
  ews_totalsubs int DEFAULT NULL,
  ottrevenue decimal(13,2) DEFAULT NULL,
  ottshare decimal(13,2) DEFAULT NULL,
  ott_totalsubs int DEFAULT NULL,
  ottrevenue_prov decimal(13,2) DEFAULT NULL,
  ottprovshare decimal(13,2) DEFAULT NULL,
  pgroupid int DEFAULT NULL,
  anp_invoiceno varchar(50) DEFAULT NULL,
  -- Primary key constraint
CONSTRAINT pk_fin_lcoinvoicing PRIMARY KEY (fin_lcoinvoicing_id)
);


-- Table : fin_mspinvoicing
DROP TABLE IF EXISTS fin_mspinvoicing CASCADE;

CREATE TABLE fin_mspinvoicing (
  fin_mspinvoicing_id UUID DEFAULT gen_random_uuid() NOT NULL,
  slno SERIAL,
  subtype INT DEFAULT 1,
  invoicemonth varchar(20) DEFAULT NULL,
  status varchar(30) DEFAULT NULL,
  state varchar(50) DEFAULT NULL,
  address varchar(300) DEFAULT NULL,
  remarks varchar(100) DEFAULT NULL,
  mspid bigint DEFAULT NULL,
  designation varchar(50) DEFAULT NULL,
  verifiedby varchar(50) DEFAULT NULL,
  approvedate timestamp DEFAULT NULL,
  invoiceno varchar(50) DEFAULT NULL,
  nettotal decimal(10,2) DEFAULT NULL,
  STtotal decimal(10,2) DEFAULT NULL,
  GrossTotal decimal(10,2) DEFAULT NULL,
  dot decimal(10,2) DEFAULT NULL,
  agrtotal decimal(10,2) DEFAULT NULL,
  mktshare decimal(10,2) DEFAULT NULL,
  mspshare decimal(10,2) DEFAULT NULL,
  netshare decimal(10,2) DEFAULT NULL,
  STpartner decimal(10,2) DEFAULT NULL,
  GrossShare decimal(10,2) DEFAULT NULL,
  TDSpartner decimal(10,2) DEFAULT NULL,
  NetPayable decimal(10,2) DEFAULT NULL,
  STno varchar(25) DEFAULT NULL,
  Pan varchar(12) DEFAULT NULL,
  requestdate timestamp DEFAULT NULL,
  edcess decimal(10,2) DEFAULT NULL,
  secedcess decimal(10,2) DEFAULT NULL,
  STpartnertotal decimal(10,2) DEFAULT NULL,
  prsshare decimal(10,2) DEFAULT NULL,
  modifiedby varchar(50) DEFAULT NULL,
  modifiedon timestamp DEFAULT NULL,
  spocapproval varchar(30) DEFAULT NULL,
  spocapproval_date timestamp DEFAULT NULL,
  rrit_response varchar(300) DEFAULT NULL,
  rrit_response_date timestamp DEFAULT NULL,
  mspresponse varchar(300) DEFAULT NULL,
  msp_response_date timestamp DEFAULT NULL,
  spocremark varchar(300) DEFAULT NULL,
  gsround decimal(10,2) DEFAULT NULL,
  tdsround decimal(10,2) DEFAULT NULL,
  spocresponse varchar(300) DEFAULT NULL,
  sbcess decimal(10,2) DEFAULT 0.00,
  kkcess decimal(10,2) DEFAULT NULL,
  companyname varchar(120) DEFAULT NULL,
  companyaddress varchar(180) DEFAULT NULL,
  bank_name varchar(120) DEFAULT NULL,
  bank_branch varchar(120) DEFAULT NULL,
  bank_account varchar(45) DEFAULT NULL,
  bank_beneficiray varchar(120) DEFAULT NULL,
  bank_ifsc varchar(120) DEFAULT NULL,
  gst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  cgst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  sgst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  igst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  gst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  cgst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  sgst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  igst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  paid_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  gstin varchar(15) DEFAULT NULL,
  gst_disburse_status INT NOT NULL DEFAULT 0,
  STCode char(3) DEFAULT NULL,
  pst_code char(3) DEFAULT NULL,
  taxpayertype INT NOT NULL DEFAULT 0,
  gst_disbursedate timestamp DEFAULT NULL,
  sgsttds_amount decimal(13,2) DEFAULT 0.00,
  cgsttds_amount decimal(13,2) DEFAULT 0.00,
  cashbackrev decimal(10,2) DEFAULT NULL,
  Normalrevenue decimal(12,2) DEFAULT NULL,
  -- Primary key constraint
CONSTRAINT pk_fin_mspinvoicing PRIMARY KEY (fin_mspinvoicing_id)
);


-- Table : fin_ottinvoice
DROP TABLE IF EXISTS fin_ottinvoice CASCADE;

CREATE TABLE fin_ottinvoice (
  fin_ottinvoice_id UUID DEFAULT gen_random_uuid() NOT NULL,
  slno SERIAL,
  providerid bigint DEFAULT NULL,
  invoicemonth varchar(20) DEFAULT NULL,
  status INT DEFAULT NULL,
  state varchar(50) DEFAULT NULL,
  invoiceno varchar(50) DEFAULT NULL,
  offlinerevenue decimal(12,4) DEFAULT NULL,
  onlinerevenue decimal(12,4) DEFAULT NULL,
  nettotal decimal(12,4) DEFAULT NULL,
  STtotal decimal(10,2) DEFAULT NULL,
  GrossTotal decimal(12,4) DEFAULT NULL,
  dot decimal(12,4) DEFAULT NULL,
  agrtotal decimal(12,4) DEFAULT NULL,
  netshare decimal(12,4) DEFAULT NULL,
  gst_rate decimal(12,4) NOT NULL DEFAULT 0.0000,
  cgst_rate decimal(12,4) NOT NULL DEFAULT 0.0000,
  sgst_rate decimal(12,4) NOT NULL DEFAULT 0.0000,
  igst_rate decimal(12,4) NOT NULL DEFAULT 0.0000,
  gst_amount decimal(12,4) NOT NULL DEFAULT 0.0000,
  cgst_amount decimal(12,4) NOT NULL DEFAULT 0.0000,
  sgst_amount decimal(12,4) NOT NULL DEFAULT 0.0000,
  igst_amount decimal(12,4) NOT NULL DEFAULT 0.0000,
  GrossShare decimal(12,4) DEFAULT NULL,
  TDSpartner decimal(12,4) DEFAULT NULL,
  NetPayable decimal(12,4) DEFAULT NULL,
  Pan varchar(12) DEFAULT NULL,
  gstin varchar(15) DEFAULT NULL,
  taxpayertype INT NOT NULL DEFAULT 0,
  paid_amount decimal(12,4) NOT NULL DEFAULT 0.0000,
  pst_code char(3) DEFAULT NULL,
  cgsttds_amount decimal(12,4) NOT NULL DEFAULT 0.0000,
  sgsttds_amount decimal(12,4) NOT NULL DEFAULT 0.0000,
  revenue_type varchar(10) DEFAULT NULL,
  -- Primary key constraint
CONSTRAINT pk_fin_ottinvoice PRIMARY KEY (fin_ottinvoice_id)
);


-- Table : flatincentive
DROP TABLE IF EXISTS flatincentive CASCADE;

CREATE TABLE flatincentive (
  flatincentive_id UUID DEFAULT gen_random_uuid() NOT NULL,
  slno SERIAL,
  partnerid bigint DEFAULT NULL,
  pgid bigint DEFAULT NULL,
  subscriberid bigint DEFAULT NULL,
  invoiceid bigint DEFAULT NULL,
  rectype INT DEFAULT NULL,
  revenue decimal(10,4) DEFAULT NULL,
  dot decimal(10,4) DEFAULT NULL,
  agr decimal(10,4) DEFAULT NULL,
  incentive decimal(10,4) DEFAULT NULL,
  tds decimal(10,4) DEFAULT NULL,
  paid_amount decimal(10,4) DEFAULT NULL,
  monthpart varchar(10) DEFAULT NULL,
  slab INT DEFAULT NULL,
  incentive_category INT DEFAULT NULL,
  -- '1 - Revenue share, 2 - Acquisition, 3 - Quaterly retention',
  create_date timestamp DEFAULT CURRENT_TIMESTAMP,
  update_date timestamp DEFAULT CURRENT_TIMESTAMP,
  -- Primary key constraint
CONSTRAINT pk_flatincentive PRIMARY KEY (flatincentive_id)
);


-- Table : flatincentive_breakup
DROP TABLE IF EXISTS flatincentive_breakup CASCADE;

CREATE TABLE flatincentive_breakup (
  flatincentive_breakup_id UUID DEFAULT gen_random_uuid() NOT NULL,
  id SERIAL,
  category INT DEFAULT NULL,
  subscribercount int DEFAULT NULL,
  lnpid bigint DEFAULT NULL,
  revenue decimal(10,4) DEFAULT NULL,
  dot decimal(10,4) DEFAULT NULL,
  agr decimal(10,4) DEFAULT NULL,
  incentive decimal(10,4) DEFAULT NULL,
  tds decimal(10,4) DEFAULT NULL,
  incentive_lesstds decimal(10,4) DEFAULT NULL,
  monthpart varchar(20) DEFAULT NULL,
  create_date timestamp DEFAULT CURRENT_TIMESTAMP,
  update_date timestamp DEFAULT CURRENT_TIMESTAMP,
  -- Primary key constraint
CONSTRAINT pk_flatincentive_breakup PRIMARY KEY (flatincentive_breakup_id)
);


-- Table : floor
DROP TABLE IF EXISTS floor CASCADE;

CREATE TABLE floor (
  floor_id UUID DEFAULT gen_random_uuid() NOT NULL,
  floorid SERIAL,
  floorname varchar(250) DEFAULT NULL,
  -- Primary key constraint
CONSTRAINT pk_floor PRIMARY KEY (floor_id)
);