DROP TABLE IF EXISTS cor_fin_agpinvoicing_q CASCADE;

CREATE TABLE cor_fin_agpinvoicing_q (
  id UUID NOT NULL,
  slno SERIAL,
  invoicemonth varchar(45) DEFAULT NULL,
  status int DEFAULT NULL,
  state varchar(50) DEFAULT NULL,
  remarks varchar(100) DEFAULT NULL,
  agpid bigint DEFAULT NULL,
  designation varchar(50) DEFAULT NULL,
  verifiedby varchar(50) DEFAULT NULL,
  approvedate timestamp DEFAULT NULL,
  invoiceno varchar(50) DEFAULT NULL,
  nettotal decimal(10,2) DEFAULT NULL,
  STtotal decimal(10,2) DEFAULT NULL,
  GrossTotal decimal(10,2) DEFAULT NULL,
  dot decimal(10,2) DEFAULT NULL,
  agrtotal decimal(10,2) DEFAULT NULL,
  agpshare decimal(10,2) DEFAULT NULL,
  netshare decimal(10,2) DEFAULT NULL,
  STpartner decimal(10,2) DEFAULT NULL,
  GrossShare decimal(10,2) DEFAULT NULL,
  TDSpartner decimal(10,2) DEFAULT NULL,
  NetPayable decimal(10,2) DEFAULT NULL,
  STno varchar(100) DEFAULT NULL,
  Pan varchar(20) DEFAULT NULL,
  requestdate timestamp DEFAULT NULL,
  response varchar(300) DEFAULT NULL,
  responsedate timestamp DEFAULT NULL,
  spocapproval int NOT NULL DEFAULT 0,
  spocapprove_date timestamp DEFAULT NULL,
  spocremark varchar(300) DEFAULT NULL,
  mspresponse varchar(300) DEFAULT NULL,
  tmapproval int NOT NULL DEFAULT 0,
  tmremark varchar(300) DEFAULT NULL,
  tmresponse varchar(300) DEFAULT NULL,
  spocresponse varchar(300) NOT NULL,
  mspagpresponse varchar(300) NOT NULL,
  workorderid varchar(45) DEFAULT NULL,
  CONSTRAINT pk_cor_fin_agpinvoicing_q PRIMARY KEY (id)
);


DROP TABLE IF EXISTS cor_fin_lcoinvoicing CASCADE;

CREATE TABLE cor_fin_lcoinvoicing (
  id UUID NOT NULL,
  slno SERIAL,
  subgroup smallint DEFAULT NULL,
  pgroupid int DEFAULT NULL,
  total_locations int DEFAULT NULL,
  invoicemonth varchar(20) DEFAULT NULL,
  invoicedate date DEFAULT NULL,
  status int DEFAULT NULL,
  state varchar(50) DEFAULT NULL,
  remarks varchar(100) DEFAULT NULL,
  partnerid bigint DEFAULT NULL,
  designation varchar(50) DEFAULT NULL,
  verifiedby varchar(50) DEFAULT NULL,
  approvedate timestamp DEFAULT NULL,
  invoiceno varchar(50) DEFAULT NULL,
  nettotal decimal(10,2) DEFAULT NULL,
  STtotal decimal(10,2) DEFAULT NULL,
  GrossTotal decimal(10,2) DEFAULT NULL,
  dot decimal(10,2) DEFAULT NULL,
  agrtotal decimal(10,2) DEFAULT NULL,
  ibnpshare decimal(10,2) DEFAULT NULL,
  anpshare decimal(10,2) DEFAULT NULL,
  netshare decimal(10,2) DEFAULT NULL,
  STpartner decimal(10,2) DEFAULT NULL,
  GrossShare decimal(10,2) DEFAULT NULL,
  TDSpartner decimal(10,2) DEFAULT NULL,
  NetPayable decimal(10,2) DEFAULT NULL,
  STno varchar(100) DEFAULT NULL,
  Pan varchar(20) DEFAULT NULL,
  requestdate timestamp DEFAULT NULL,
  cnpshare decimal(10,2) DEFAULT NULL,
  agnpshare decimal(10,2) DEFAULT NULL,
  mktshare decimal(10,2) DEFAULT NULL,
  prsshare decimal(10,2) DEFAULT NULL,
  mspshare decimal(10,2) DEFAULT NULL,
  workorderid varchar(45) DEFAULT NULL,
  otc decimal(10,2) DEFAULT NULL,
  lcototal decimal(10,2) DEFAULT NULL,
  sbcess decimal(10,2) DEFAULT NULL,
  pdate timestamp DEFAULT NULL,
  pstatus int DEFAULT 0,
  pamount decimal(10,2) DEFAULT NULL,
  kkcess decimal(10,2) DEFAULT NULL,
  paymode varchar(100) DEFAULT NULL,
  deemedappvdate timestamp DEFAULT NULL,
  pst_code char(3) DEFAULT NULL,
  gst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  cgst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  sgst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  igst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  gst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  cgst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  sgst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  igst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  gstin varchar(15) DEFAULT NULL,
  gst_disburse_status boolean NOT NULL DEFAULT false,
  STCode char(3) DEFAULT NULL,
  paid_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  taxpayertype boolean NOT NULL DEFAULT false,
  gst_disbursedate timestamp DEFAULT NULL,
  special_month varchar(250) DEFAULT NULL,
  cgsttds_amount decimal(13,2) DEFAULT NULL,
  sgsttds_amount decimal(13,2) DEFAULT NULL,
  uptime decimal(5,2) DEFAULT NULL,
  penalty_percentage int DEFAULT 0,
  penalty_amount decimal(13,2) DEFAULT 0.00,
  anp_invoiceno varchar(50) DEFAULT NULL,
  response varchar(256) DEFAULT NULL,
  responsedate timestamp DEFAULT NULL,
  createdate timestamp DEFAULT CURRENT_TIMESTAMP,
  updatedate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_active boolean DEFAULT true,
  CONSTRAINT pk_cor_fin_lcoinvoicing PRIMARY KEY (id)
);


DROP TABLE IF EXISTS cor_fin_lcoinvoicing_q CASCADE;

CREATE TABLE cor_fin_lcoinvoicing_q (
  id UUID NOT NULL,
  slno SERIAL,
  invoicemonth varchar(45) DEFAULT NULL,
  status int DEFAULT NULL,
  state varchar(50) DEFAULT NULL,
  remarks varchar(100) DEFAULT NULL,
  partnerid bigint DEFAULT NULL,
  designation varchar(50) DEFAULT NULL,
  verifiedby varchar(50) DEFAULT NULL,
  approvedate timestamp DEFAULT NULL,
  invoiceno varchar(50) DEFAULT NULL,
  nettotal decimal(10,2) DEFAULT NULL,
  STtotal decimal(10,2) DEFAULT NULL,
  GrossTotal decimal(10,2) DEFAULT NULL,
  dot decimal(10,2) DEFAULT NULL,
  agrtotal decimal(10,2) DEFAULT NULL,
  ibnpshare decimal(10,2) DEFAULT NULL,
  anpshare decimal(10,2) DEFAULT NULL,
  netshare decimal(10,2) DEFAULT NULL,
  STpartner decimal(10,2) DEFAULT NULL,
  GrossShare decimal(10,2) DEFAULT NULL,
  TDSpartner decimal(10,2) DEFAULT NULL,
  NetPayable decimal(10,2) DEFAULT NULL,
  STno varchar(100) DEFAULT NULL,
  Pan varchar(20) DEFAULT NULL,
  requestdate timestamp DEFAULT NULL,
  cnpshare decimal(10,2) DEFAULT NULL,
  agnpshare decimal(10,2) DEFAULT NULL,
  mktshare decimal(10,2) DEFAULT NULL,
  prsshare decimal(10,2) DEFAULT NULL,
  mspshare decimal(10,2) DEFAULT NULL,
  workorderid varchar(45) DEFAULT NULL,
  otc decimal(10,2) DEFAULT NULL,
  lcototal decimal(10,2) DEFAULT NULL,
  CONSTRAINT pk_cor_fin_lcoinvoicing_q PRIMARY KEY (id)
);


DROP TABLE IF EXISTS cor_fin_mspinvoicing CASCADE;

CREATE TABLE cor_fin_mspinvoicing (
  id UUID NOT NULL,
  slno SERIAL,
  subgroup boolean DEFAULT NULL,
  invoicemonth varchar(20) DEFAULT NULL,
  invoicedate date DEFAULT NULL,
  status varchar(30) DEFAULT NULL,
  state varchar(50) DEFAULT NULL,
  remarks varchar(100) DEFAULT NULL,
  mspid bigint DEFAULT NULL,
  designation varchar(50) DEFAULT NULL,
  verifiedby varchar(50) DEFAULT NULL,
  approvedate timestamp DEFAULT NULL,
  invoiceno varchar(50) DEFAULT NULL,
  nettotal decimal(10,2) DEFAULT NULL,
  STtotal decimal(10,2) DEFAULT NULL,
  GrossTotal decimal(10,2) DEFAULT NULL,
  dot decimal(10,2) DEFAULT NULL,
  agrtotal decimal(10,2) DEFAULT NULL,
  mktshare decimal(10,2) DEFAULT NULL,
  mspshare decimal(10,2) DEFAULT NULL,
  netshare decimal(10,2) DEFAULT NULL,
  STpartner decimal(10,2) DEFAULT NULL,
  GrossShare decimal(10,2) DEFAULT NULL,
  TDSpartner decimal(10,2) DEFAULT NULL,
  NetPayable decimal(10,2) DEFAULT NULL,
  STno varchar(30) DEFAULT NULL,
  Pan varchar(20) DEFAULT NULL,
  requestdate timestamp DEFAULT NULL,
  edcess decimal(10,2) DEFAULT NULL,
  secedcess decimal(10,2) DEFAULT NULL,
  STpartnertotal decimal(10,2) DEFAULT NULL,
  prsshare decimal(10,2) DEFAULT NULL,
  modifiedby varchar(50) DEFAULT NULL,
  modifiedon timestamp DEFAULT NULL,
  spocapproval int DEFAULT NULL,
  spocapproval_date timestamp DEFAULT NULL,
  rrit_response varchar(300) DEFAULT NULL,
  rrit_response_date timestamp DEFAULT NULL,
  mspresponse varchar(300) DEFAULT NULL,
  msp_response_date timestamp DEFAULT NULL,
  spocremark varchar(300) DEFAULT NULL,
  spocresponse varchar(300) DEFAULT NULL,
  workorderid varchar(45) DEFAULT NULL,
  sbcess decimal(10,2) DEFAULT 0.00,
  kkcess decimal(10,2) DEFAULT NULL,
  pamount decimal(10,2) DEFAULT NULL,
  gst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  cgst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  sgst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  igst_rate decimal(13,2) NOT NULL DEFAULT 0.00,
  gst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  cgst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  sgst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  igst_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  gstin varchar(15) DEFAULT NULL,
  gst_disburse_status boolean NOT NULL DEFAULT false,
  STCode char(3) DEFAULT NULL,
  paid_amount decimal(13,2) NOT NULL DEFAULT 0.00,
  taxpayertype boolean NOT NULL DEFAULT false,
  gst_disbursedate timestamp DEFAULT NULL,
  special_month varchar(250) DEFAULT NULL,
  cgsttds_amount decimal(13,2) DEFAULT NULL,
  sgsttds_amount decimal(13,2) DEFAULT NULL,
  CONSTRAINT pk_cor_fin_mspinvoicing PRIMARY KEY (id)
);