apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  KL_POSTGRES_URL: "jdbc:postgresql://{{ required "app.tenants.KL.host is required" .Values.app.tenants.KL.host }}:{{ default 5432 .Values.app.tenants.KL.port }}/{{ required "app.tenants.KL.name is required" .Values.app.tenants.KL.name }}?sslmode={{ default "require" .Values.app.tenants.KL.sslmode }}"
  KL_POSTGRES_USER: { { required "app.tenants.KL.user is required" .Values.app.tenants.KL.user | quote } }
  KL_POSTGRES_PASSWORD: { { required "app.tenants.KL.password is required" .Values.app.tenants.KL.password | quote } }
  LD_POSTGRES_URL: "jdbc:postgresql://{{ required "app.tenants.LD.host is required" .Values.app.tenants.LD.host }}:{{ default 5432 .Values.app.tenants.LD.port }}/{{ required "app.tenants.LD.name is required" .Values.app.tenants.LD.name }}?sslmode={{ default "require" .Values.app.tenants.LD.sslmode }}"
  LD_POSTGRES_USER: { { required "app.tenants.LD.user is required" .Values.app.tenants.LD.user | quote } }
  LD_POSTGRES_PASSWORD: { { required "app.tenants.LD.password is required" .Values.app.tenants.LD.password | quote } }
